### ISSUE TITLE
[BUG] Unicode characters in filename cause service to freeze

### ISSUE THREAD

**Issue by rednessreliever** [ipsingh06/seedsync#36] opened 2019-04-16 04:19 UTC
There is a problem with handling Unicode characters in filenames which cause the process to freeze, requiring a restart. Consider the following filename:

`Gloria (André Luguet, Mady Berry, Jean Gabin 1931).avi`

SeedSync will strip out the character `é` such that the following error occurs:

```
2019/MM/DD HH:MM:SS - ERROR - seedsync - Caught exception Traceback (most recent call last):
  File "/app/python/seedsync.py", line 162, in run
    controller_job.propagate_exception()
  File "/app/python/common/job.py", line 77, in propagate_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/app/python/common/job.py", line 44, in run
    self.execute()
  File "/app/python/controller/controller_job.py", line 29, in execute
    self.__controller.process()
  File "/app/python/controller/controller.py", line 199, in process
    self.__propagate_exceptions()
  File "/app/python/controller/controller.py", line 521, in __propagate_exceptions
    self.__lftp.raise_pending_error()
  File "/app/python/lftp/lftp.py", line 114, in raise_pending_error
    raise LftpError(error)
lftp.lftp.LftpError: pget: Access failed: No such file (/Gloria (Andr Luguet, Mady Berry, Jean Gabin 1931).avi)
```
Note the missing character in the filename.

One must manually rename the file on the remote filesystem to remove the "missing" characters, and then restore them once on the local filesystem (if performing a hash check for seeding locally). It would be a minor annoyance if SeedSync skipped the failed download, but at this time all downloads halt and the service must be restarted to continue.

**Comment by naisspas** [comment] 2020-01-04 14:35
Exactly the same problem here !

**Comment by flatlinebb** [comment] 2020-06-26 18:59
I might be having a similar issue. Please let me know if this is relatred, or if I should open a separate issue.
Log file:
```
Traceback (most recent call last):


  File "/app/python/seedsync.py", line 376, in <module>


    seedsync = Seedsync()


  File "/app/python/seedsync.py", line 101, in __init__


    self.controller_persist = self._load_persist(ControllerPersist, self.controller_persist_path)


  File "/app/python/seedsync.py", line 339, in _load_persist


    return cls.from_file(file_path)


  File "/app/python/common/persist.py", line 50, in from_file


    return cls.from_str(f.read())


  File "/usr/lib/python3.7/codecs.py", line 322, in decode


    (result, consumed) = self._buffer_decode(data, self.errors, final)


UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd9 in position 77824: invalid continuation byte


      ```

**Comment by ipsingh06** [comment] 2020-06-26 21:50
@flatlinebb This is a different issue. It looks like one of your settings file is corrupted. Try deleting the `controller.persist` file and restarting Seedsync. If it still happens please create a new ticket.
The original problem of unicode handling doesn't seem to be reproducible anymore. I will close this ticket for now.

**Closed** 2020-06-26 21:50 UTC
Labels: bug
