### ISSUE TITLE
scanfs for ASUSWRT-Merlin

### ISSUE THREAD

**Issue by NoiseOver** [ipsingh06/seedsync#100] opened 2021-06-06 21:55 UTC
Hi!
Would that be possible to build scanfs supporting MIPS architecture? My seedbox is basically ASUS router (AC66U). Alternatively, is this possible to run Seedsync with no remote scanfs? Perhaps with simplified functionality...
Thanks!

**Comment by ipsingh06** [comment] 2021-06-06 23:44
Hi @NoiseOver. We use buildx for multi-arch builds, which [supports](https://docs.docker.com/desktop/multi-arch/) MIPS, so it's certainly possible. It's a matter of being able to select at runtime which binary is installed. There is already an issue tracking this, I will add this request to that one.

**Comment by ipsingh06** [comment] 2021-06-06 23:45
Duplicate of #69

**Closed as completed by ipsingh06** 2021-06-06 23:45 UTC
